// src/converter/countryMap.js
// Provides comprehensive mapping between Opera PMS guest nationality inputs
// and the 205 official country records in Sheet 'Lookup' of 'dklt nc ngoài.xlsx'.

const RAW_LOOKUP_COUNTRY_STRINGS = [
  'AFG - Afghanistan',
  'ALB - Albania',
  'DZA - Algeria',
  'AND - Andorra',
  'AGO - Angola',
  'ATG - Antigua and Barbuda',
  'ARG - Argentina',
  'ARM - Armenia',
  'AUS - Australia',
  'AUT - Austria',
  'AZE - Azerbaijan',
  'BHS - Bahamas',
  'BHR - Bahrain',
  'BGD - Bangladesh',
  'BRB - Barbados',
  'BLR - Belarus',
  'BEL - Belgium',
  'BLZ - Belize',
  'BEN - Benin',
  'BMU - Bermuda',
  'BTN - Bhutan',
  'BOL - Bolivia',
  'BIH - Bosnia and Herzegovina',
  'BWA - Botswana',
  'BRA - Brazil',
  'IOT - British India Ocean Territory',
  'BRN - Bruney',
  'BGR - Bulgaria',
  'BFA - Burkina Faso',
  'BDI - Burundi',
  'KHM - Cambodia',
  'CMR - Cameroon',
  'CAN - Canada',
  'CPV - Cape Verde',
  'CAF - Central African Republic',
  'TCD - Chad',
  'CHL - Chile',
  'CHN - China',
  'COL - Colombia',
  'COM - Comoros',
  'COG - Congo',
  'CRI - Costa Rica',
  'CIV - Cote d\' Ivoire',
  'HRV - Croatia',
  'CUB - Cuba',
  'CYP - Cyprus',
  'CZE - Czech Republic',
  'COD - Democratic Republic of the Congo',
  'DNK - Denmark',
  'DJI - Djibouti',
  'DMA - Dominica',
  'DOM - Dominican Republic',
  'ECU - Ecuador',
  'EGY - Egypt',
  'SLV - El Salvado',
  'GNQ - Equatorial Guinea',
  'ERI - Eritrea',
  'EST - Estonia',
  'ETH - Ethiopia',
  'FJI - Fiji',
  'FIN - Finland',
  'FRA - France',
  'GAB - Gabon',
  'GMB - Gambia',
  'GEO - Georgia',
  'D - Germany',
  'GHA - Ghana',
  'GIB - Gibraltar',
  'GRC - Greece',
  'GRL - Greenland',
  'GRD - Grenada',
  'GTM - Guatemala',
  'GIN - Guinea',
  'GNB - Guinea-Bissau',
  'GUY - Guyana',
  'HTI - Haiti',
  'VAT - Holy See (Vatican City State )',
  'HND - Honduras',
  'HUN - Hungary',
  'ISL - Iceland',
  'IND - India',
  'IDN - Indonesia',
  'IRN - Iran Ilasmic Republic of',
  'IRQ - Iraq',
  'IRL - Ireland',
  'ISR - Israel',
  'ITA - Italy',
  'JAM - Jamaica',
  'JPN - Japan',
  'JOR - Jordan',
  'KAZ - Kazakhstan',
  'KEN - Kenya',
  'KIR - Kiribati',
  'KOR - Korea (South)',
  'PRK - Korea Democratic Peoples Republic of',
  'RKS - Kosovo',
  'KWT - Kuwait',
  'KGZ - Kyrgyzstan',
  'LAO - Lao Peoples Democratic Republic',
  'LVA - Latvia',
  'LBN - Lebanon',
  'LSO - Lesotho',
  'LBR - Liberia',
  'LBY - Libyan Arab Jamahiriya',
  'LIE - Liechtenstein',
  'LTU - Lithuania',
  'LUX - Luxembourg',
  'MKD - Macedonia',
  'MDG - Madagascar',
  'MWI - Malawi',
  'MYS - Malaysia',
  'MDV - Maldives',
  'MLI - Mali',
  'MLT - Malta',
  'MHL - Marshall Islands',
  'MRT - Mauritania',
  'MUS - Mauritius',
  'MEX - Mexico',
  'FSM - Micronesia',
  'MDA - Moldova',
  'MCO - Monaco',
  'MNG - Mongolia',
  'MNE - Montenegro',
  'MSR - Montserrat',
  'MAR - Morocco',
  'MOZ - Mozambique',
  'MMR - Myanmar',
  'NAM - Namibia',
  'NRU - Nauru',
  'NPL - Nepal',
  'NLD - Netherland',
  'NZL - New Zealand',
  'NIC - Nicaragua',
  'NER - Niger',
  'NGA - Nigeria',
  'NOR - Norway',
  'OMN - Oman',
  'PAK - Pakistan',
  'PLW - Palau',
  'PSE - Palestine',
  'PAN - Panama',
  'PNG - Papua New Guinea',
  'PRY - Paraguay',
  'PER - Peru',
  'PHL - Philippines',
  'POL - Poland',
  'PRT - Portugal',
  'QAT - Qatar',
  'ROU - Romania',
  'RUS - Russia',
  'RWA - Rwanda',
  'KNA - Saint Kitts and Nevis',
  'LCA - Saint Lucia',
  'VCT - Saint Vincent and the Grenadines',
  'SMR - San Marino',
  'STP - Sao Tome and Principe',
  'SAU - Saudi Arabia',
  'SC- - Scotland',
  'SEN - Senegal',
  'SRB - Serbia',
  'SYC - Seychelles',
  'SLE - Sierra Leone',
  'SGP - Singapore',
  'SVK - Slovakia',
  'SVN - Slovenia',
  'SLB - Solomon Islands',
  'SOM - Somalia',
  'ZAF - South Africa',
  'SSD - South Sudan',
  'ESP - Spain',
  'LKA - Sri Lanka',
  'SDN - Sudan',
  'SUR - Suriname',
  'SWZ - Swaziland',
  'SWE - Sweden',
  'CHE - Switzerland',
  'SYR - Syrian Arab Republic',
  'TWN - Taiwan',
  'TJK - Tajikistan',
  'TZA - Tanzania United Republic of',
  'THA - Thailand',
  'TLS - Timor Leste',
  'TGO - Togo',
  'TON - Tonga',
  'TTO - Trinidad and Tobago',
  'TUN - Tunisia',
  'TUR - Turkey',
  'TKM - Turkmenistan',
  'TUV - Tuvalu',
  'UGA - Uganda',
  'UKR - Ukraine',
  'ARE - United Arab Emirates',
  'GBD - United Kingdom British Territories Citizen',
  'GBR - United Kingdom of Great Britain and Northern Ireland',
  'UNO - United Nations Organization',
  'USA - United States of America',
  'URY - Uruguay',
  'UZB - Uzbekistan',
  'VUT - Vanuatu',
  'VEN - Venezuela',
  'VNM - Viet Nam',
  'WSM - Western Samoa',
  'YEM - Yemen',
  'ZMB - Zambia',
  'ZWE - Zimbabwe'
];

// Parse canonical list into structured objects
const LOOKUP_COUNTRY_LIST = RAW_LOOKUP_COUNTRY_STRINGS.map(raw => {
  const separatorIndex = raw.indexOf(' - ');
  const code = raw.slice(0, separatorIndex).trim();
  const name = raw.slice(separatorIndex + 3).trim();
  return {
    code,
    name,
    display: raw
  };
});

// Map of ISO 3166-1 alpha-2 (2 letters) to the canonical code in Lookup sheet
const ISO2_TO_CANONICAL_CODE = {
  'AF': 'AFG',
  'AL': 'ALB',
  'DZ': 'DZA',
  'AD': 'AND',
  'AO': 'AGO',
  'AG': 'ATG',
  'AR': 'ARG',
  'AM': 'ARM',
  'AU': 'AUS',
  'AT': 'AUT',
  'AZ': 'AZE',
  'BS': 'BHS',
  'BH': 'BHR',
  'BD': 'BGD',
  'BB': 'BRB',
  'BY': 'BLR',
  'BE': 'BEL',
  'BZ': 'BLZ',
  'BJ': 'BEN',
  'BM': 'BMU',
  'BT': 'BTN',
  'BO': 'BOL',
  'BA': 'BIH',
  'BW': 'BWA',
  'BR': 'BRA',
  'IO': 'IOT',
  'BN': 'BRN',
  'BG': 'BGR',
  'BF': 'BFA',
  'BI': 'BDI',
  'KH': 'KHM',
  'CM': 'CMR',
  'CA': 'CAN',
  'CV': 'CPV',
  'CF': 'CAF',
  'TD': 'TCD',
  'CL': 'CHL',
  'CN': 'CHN',
  'CO': 'COL',
  'KM': 'COM',
  'CG': 'COG',
  'CR': 'CRI',
  'CI': 'CIV',
  'HR': 'HRV',
  'CU': 'CUB',
  'CY': 'CYP',
  'CZ': 'CZE',
  'CD': 'COD',
  'DK': 'DNK',
  'DJ': 'DJI',
  'DM': 'DMA',
  'DO': 'DOM',
  'EC': 'ECU',
  'EG': 'EGY',
  'SV': 'SLV',
  'GQ': 'GNQ',
  'ER': 'ERI',
  'EE': 'EST',
  'ET': 'ETH',
  'FJ': 'FJI',
  'FI': 'FIN',
  'FR': 'FRA',
  'GA': 'GAB',
  'GM': 'GMB',
  'GE': 'GEO',
  'DE': 'D',
  'GH': 'GHA',
  'GI': 'GIB',
  'GR': 'GRC',
  'GL': 'GRL',
  'GD': 'GRD',
  'GT': 'GTM',
  'GN': 'GIN',
  'GW': 'GNB',
  'GY': 'GUY',
  'HT': 'HTI',
  'VA': 'VAT',
  'HN': 'HND',
  'HU': 'HUN',
  'IS': 'ISL',
  'IN': 'IND',
  'ID': 'IDN',
  'IR': 'IRN',
  'IQ': 'IRQ',
  'IE': 'IRL',
  'IL': 'ISR',
  'IT': 'ITA',
  'JM': 'JAM',
  'JP': 'JPN',
  'JO': 'JOR',
  'KZ': 'KAZ',
  'KE': 'KEN',
  'KI': 'KIR',
  'KR': 'KOR',
  'KP': 'PRK',
  'XK': 'RKS',
  'KW': 'KWT',
  'KG': 'KGZ',
  'LA': 'LAO',
  'LV': 'LVA',
  'LB': 'LBN',
  'LS': 'LSO',
  'LR': 'LBR',
  'LY': 'LBY',
  'LI': 'LIE',
  'LT': 'LTU',
  'LU': 'LUX',
  'MK': 'MKD',
  'MG': 'MDG',
  'MW': 'MWI',
  'MY': 'MYS',
  'MV': 'MDV',
  'ML': 'MLI',
  'MT': 'MLT',
  'MH': 'MHL',
  'MR': 'MRT',
  'MU': 'MUS',
  'MX': 'MEX',
  'FM': 'FSM',
  'MD': 'MDA',
  'MC': 'MCO',
  'MN': 'MNG',
  'ME': 'MNE',
  'MS': 'MSR',
  'MA': 'MAR',
  'MZ': 'MOZ',
  'MM': 'MMR',
  'NA': 'NAM',
  'NR': 'NRU',
  'NP': 'NPL',
  'NL': 'NLD',
  'NZ': 'NZL',
  'NI': 'NGA', // Hotel PMS alias: Nigeria (Nicaragua uses NIC)
  'NE': 'NER',
  'NG': 'NGA',
  'NO': 'NOR',
  'OM': 'OMN',
  'PK': 'PAK',
  'PW': 'PLW',
  'PS': 'PSE',
  'PA': 'PAN',
  'PG': 'PNG',
  'PY': 'PRY',
  'PE': 'PER',
  'PH': 'PHL',
  'PL': 'POL',
  'PT': 'PRT',
  'QA': 'QAT',
  'RO': 'ROU',
  'RU': 'RUS',
  'RW': 'RWA',
  'KN': 'KNA',
  'LC': 'LCA',
  'VC': 'VCT',
  'SM': 'SMR',
  'ST': 'STP',
  'SA': 'SAU',
  'SN': 'SEN',
  'RS': 'SRB',
  'SC': 'SC-',
  'SL': 'SLE',
  'SG': 'SGP',
  'SK': 'SVK',
  'SI': 'SVN',
  'SB': 'SLB',
  'SO': 'SOM',
  'ZA': 'ZAF',
  'SS': 'SSD',
  'ES': 'ESP',
  'LK': 'LKA',
  'SD': 'SDN',
  'SR': 'SUR',
  'SZ': 'SWZ',
  'SE': 'SWE',
  'CH': 'CHE',
  'SY': 'SYR',
  'TW': 'TWN',
  'TJ': 'TJK',
  'TZ': 'TZA',
  'TH': 'THA',
  'TL': 'TLS',
  'TG': 'TGO',
  'TO': 'TON',
  'TT': 'TTO',
  'TN': 'TUN',
  'TR': 'TUR',
  'TM': 'TKM',
  'TV': 'TUV',
  'UG': 'UGA',
  'UA': 'UKR',
  'AE': 'ARE',
  'GB': 'GBR',
  'US': 'USA',
  'UY': 'URY',
  'UZ': 'UZB',
  'VU': 'VUT',
  'VE': 'VEN',
  'VN': 'VNM',
  'WS': 'WSM',
  'YE': 'YEM',
  'ZM': 'ZMB',
  'ZW': 'ZWE'
};

// Hotel PMS aliases, historical/alternative country names and territories
const HOTEL_AND_TERRITORY_ALIASES = {
  'UK': 'GBR',
  'DEU': 'D',
  'GERMANY': 'D',
  'ENGLAND': 'GBR',
  'GREAT BRITAIN': 'GBR',
  'BRITAIN': 'GBR',
  'UNITED KINGDOM': 'GBR',
  'SCOTLAND': 'SC-',
  'HK': 'CHN',
  'HKG': 'CHN',
  'HONG KONG': 'CHN',
  'HONGKONG': 'CHN',
  'MO': 'CHN',
  'MAC': 'CHN',
  'MACAU': 'CHN',
  'MACAO': 'CHN',
  'SOUTH KOREA': 'KOR',
  'KOREA': 'KOR',
  'REPUBLIC OF KOREA': 'KOR',
  'KOREA REPUBLIC OF': 'KOR',
  'KOREA (SOUTH)': 'KOR',
  'NORTH KOREA': 'PRK',
  'DEMOCRATIC PEOPLES REPUBLIC OF KOREA': 'PRK',
  'DPRK': 'PRK',
  'TAIWAN': 'TWN',
  'ROC': 'TWN',
  'RUSSIA': 'RUS',
  'RUSSIAN FEDERATION': 'RUS',
  'LAOS': 'LAO',
  'BRUNEI': 'BRN',
  'BRUNEI DARUSSALAM': 'BRN',
  'CZECHIA': 'CZE',
  'HOLLAND': 'NLD',
  'NETHERLANDS': 'NLD',
  'THE NETHERLANDS': 'NLD',
  'BURMA': 'MMR',
  'SWITZERLAND': 'CHE',
  'UAE': 'ARE',
  'AMERICA': 'USA',
  'USA': 'USA',
  'VIETNAM': 'VNM',
  'VIET NAM': 'VNM',
  'PHILIPPINES': 'PHL',
  'SINGAPORE': 'SGP',
  'MALAYSIA': 'MYS',
  'INDONESIA': 'IDN',
  'THAILAND': 'THA',
  'JAPAN': 'JPN',
  'CHINA': 'CHN',
  'AUSTRALIA': 'AUS',
  'FRANCE': 'FRA',
  'CANADA': 'CAN',
  'ITALY': 'ITA',
  'SPAIN': 'ESP',
  'INDIA': 'IND'
};

// Fast inverted index: maps any normalized key -> canonical display string
const COUNTRY_INDEX = new Map();
const CODE_TO_CANONICAL = new Map();

// 1. Populate canonical records
LOOKUP_COUNTRY_LIST.forEach(item => {
  CODE_TO_CANONICAL.set(item.code.toUpperCase(), item.display);
  COUNTRY_INDEX.set(item.display.toUpperCase(), item.display);
  COUNTRY_INDEX.set(item.code.toUpperCase(), item.display);
  COUNTRY_INDEX.set(item.name.toUpperCase(), item.display);
});

// 2. Populate ISO-2 codes
Object.entries(ISO2_TO_CANONICAL_CODE).forEach(([iso2, code]) => {
  const display = CODE_TO_CANONICAL.get(code.toUpperCase());
  if (display) {
    COUNTRY_INDEX.set(iso2.toUpperCase(), display);
  }
});

// 3. Populate aliases
Object.entries(HOTEL_AND_TERRITORY_ALIASES).forEach(([alias, code]) => {
  const display = CODE_TO_CANONICAL.get(code.toUpperCase());
  if (display) {
    COUNTRY_INDEX.set(alias.toUpperCase(), display);
  }
});

/**
 * Normalizes foreign guest country inputs (ISO-2, ISO-3, names, PMS aliases)
 * to the exact format in the 'Lookup' sheet of 'dklt nc ngoài.xlsx'.
 *
 * @param {string} rawInput Raw country string or code
 * @returns {string} Formatted country (e.g. 'TWN - Taiwan', 'NGA - Nigeria') or original string fallback
 */
function normalizeForeignCountry(rawInput) {
  if (rawInput === null || rawInput === undefined) return '';
  const trimmed = String(rawInput).trim();
  if (!trimmed) return '';

  const cleaned = trimmed.toUpperCase();

  // 1. Exact match in index (handles display, ISO-2, ISO-3, aliases, names)
  if (COUNTRY_INDEX.has(cleaned)) {
    return COUNTRY_INDEX.get(cleaned);
  }

  // 2. Simplified punctuation / whitespace (e.g. "Korea, Republic of" or "Cote d'Ivoire")
  const simplified = cleaned
    .replace(/[,\.\(\)\-_']/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  if (COUNTRY_INDEX.has(simplified)) {
    return COUNTRY_INDEX.get(simplified);
  }

  // 3. Fallback: Return original trimmed string
  return trimmed;
}

module.exports = {
  LOOKUP_COUNTRY_LIST,
  COUNTRY_INDEX,
  normalizeForeignCountry
};
